name: cleanup-artifacts
description: hello

runs:
  using: composite
  steps:
    - name: setup
      id: setup
      shell: bash
      env: 
        runnerJson: "${{ toJson(runner)}}"
      run: |
        echo $runnerJson