# clean artifactsアクション (Composite)
# 処理内容:
#   - 指定されたrun_idで作成された成果物を全て削除
#   - actions/github-scriptを使用してGitHub APIを呼び出し
# パラメータ:
#   - gh-token: GitHub Token
# outputs: なし

name: 'clean artifacts'
description: 'Clean Artifacts Action'

inputs:
  gh-token:
    required: true

runs:
  using: composite
  steps:
    - name: clean artifacts
      uses: actions/github-script@v7
      env:
        RUN_ID: ${{ github.run_id }}
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const runId = parseInt(process.env.RUN_ID);
          const [owner, repo] = '${{ github.repository }}'.split('/');
          
          console.log(`Fetching artifacts for run ID: ${runId}`);
          
          // 対象のワークフロー実行で作成された成果物を取得
          const { data: artifacts } = await github.rest.actions.listArtifactsForRepo({
            owner,
            repo
          });
          
          const targetArtifacts = artifacts.artifacts.filter(
            artifact => artifact.workflow_run.id === runId
          );
          
          if (targetArtifacts.length === 0) {
            console.log(`No artifacts found for run ID: ${runId}`);
            return;
          }
          
          console.log(`Found ${targetArtifacts.length} artifact(s) to delete`);
          
          // 各成果物を削除
          for (const artifact of targetArtifacts) {
            console.log(`Deleting artifact: ${artifact.name} (ID: ${artifact.id})`);
            await github.rest.actions.deleteArtifact({
              owner,
              repo,
              artifact_id: artifact.id
            });
          }
          
          console.log('All artifacts deleted successfully');