name: cancel-finally

on:
  workflow_dispatch:
    inputs:
      vender:
        type: choice
        required: true
        default: 'apple'
        options:
          - 'apple'
          - 'google'

jobs:
  pipeline:
    timeout-minutes: 7200
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@v6

    - name: create files
      id: create-files
      env:
        githubJson : ${{ toJson(github) }}
      run: |
        echo $githubJson |jq . > github.json
        echo ${{ inputs.vender }} > vender.txt
        echo "run url:${{ github.server_url }}//${{ github.repository }}/actions/runs/${{ github.run_id }}" > summary.txt
        echo "run number:${{ github.run_number }}" >> summary.txt
        echo "executed by":${{ github.actor }} >> summary.txt
        
    - name: short sleep
      id: sleep
      run: sleep 10

    - name: canceled summary
      if: always() && steps.sleep.outcome == 'cancelled'
      id: canceled-summary
      run: |
        echo "${{ toJson(steps.sleep) }}"
        ls -la
        echo "### Build Successful! 🚀" >> $GITHUB_STEP_SUMMARY

    - name: create summary
      id: create-summary
      if: always()
      run: |
        {
          echo "## Parameters"
          echo "vender: ${{ inputs.vender }}"
          echo ""
          echo "## Results"
          cat summary.txt
          echo ""
          echo "## Steps"
          echo '```json'
          echo '${{ toJson(steps) }}' | jq .
          echo '```'
        } >> $GITHUB_STEP_SUMMARY

    - name: upload artifact
      id: upload-artifact
      if: ${{ always() }}
      uses: actions/upload-artifact@v7
      with:
        path: |
          github.json
          vender.txt
        archive: true
        retention-days: 1
        compression-level: 0