name: cancel-finally

on:
  workflow_dispatch:
    inputs:
      vender:
        type: choice
        required: true
        default: 'apple'
        options:
          - 'apple'
          - 'google'

jobs:
  pipeline:
    timeout-minutes: 7200
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v6

    - name: create files
      env:
        githubJson : ${{ toJson(github) }}
        vender : ${{ inputs.vender }}
      run: |
        echo $githubJson |jq . > github.json
        echo $vender > vender.txt
        echo "run_url:${{ github.server_url }}/${{ github.repository_owner }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" > summary.txt

    - name: short sleep
      run: sleep 300

    - name: success summary
      run: |
        ls -la
        echo "### Build Successful! 🚀" >> $GITHUB_STEP_SUMMARY

    - name: create summary
      if: ${{ always() }}
      run: |
        ls -la
        cat summary.txt >> $GITHUB_STEP_SUMMARY
        echo "${{ toJson(steps) }}" >> $GITHUB_STEP_SUMMARY

    - name: finally
      if: ${{ always() }}
      uses: actions/upload-artifact@v7
      with:
        path: |
          github.json
          vender.txt
        archive: true
        retention-days: 1
        compression-level: 0